config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    # @new_task = Task.new(task_params)

    # if @new_task.save
    #   redirect_to root, notice: 'Restaurant was successfully created.'
    # else
    #   render :new
    # end
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def update
    if @task.update(task_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyToDoList</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles&family=Lato&family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page_container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tasks/index.html.erb
<div class="task-containers">
  <% @tasks.each do |task| %>
    <div class="task-container" data-controller="complete">
      <%= link_to  task_path(task), class: "task-title" do %>
        <h2 class="task-title" data-complete-target="output"><%= task.title %></h2>
      <% end %>
      <%= link_to task_path(task), method: :delete, remote: true  do %>
        <div class="circle" data-action="click->complete#delete"></div>
      <% end %>
    </div>
  <% end %>

  <div><%= link_to "Create New Task", new_task_path %></div>
</div>

app/views/tasks/new.html.erb
<div class="form_container">
  <%= simple_form_for [@task] do |f| %>
      <%= f.input :title %>
      <%= f.input :details %>
      <%= f.submit %>
    <% end %>
</div>

app/views/tasks/show.html.erb
<%= @task.details %>